### ISSUE TITLE
numpy 1.15.0 is required for hvplot 0.5.2

### ISSUE THREAD

**Issue by AlbertDeFusco** [holoviz/hvplot#412]
#### ALL software version info (this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

```
conda create -n hv5 python=3.6 pandas=0.25 numpy=1.13.3 hvplot=0.5.2
```

#### Description of expected behavior and the observed behavior

Conda should have failed because NumPy 1.13.3 does not support `np.nanquantile`

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import pandas as pd
import hvplot.pandas
pd.DataFrame({'x':[0,0],'y':[1,1], 'c':['a','b']}).hvplot.scatter(x='x',y='y',color='c')

```

#### Stack traceback and/or browser JavaScript console output

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    pd.DataFrame({'x':[0,0],'y':[1,1], 'c':['a','b']}).hvplot.scatter(x='x',y='y',color='c')
  File "/Users/adefusco/Applications/miniconda3/envs/hv5/lib/python3.6/site-packages/hvplot/plotting/core.py", line 191, in scatter
    return self(x, y, kind='scatter', **kwds)
  File "/Users/adefusco/Applications/miniconda3/envs/hv5/lib/python3.6/site-packages/hvplot/plotting/core.py", line 72, in __call__
    return self._get_converter(x, y, kind, **kwds)(kind, x, y)
  File "/Users/adefusco/Applications/miniconda3/envs/hv5/lib/python3.6/site-packages/hvplot/plotting/core.py", line 80, in _get_converter
    self._data, x, y, kind=kind, **params
  File "/Users/adefusco/Applications/miniconda3/envs/hv5/lib/python3.6/site-packages/hvplot/converter.py", line 460, in __init__
    symmetric = self._process_symmetric(symmetric, clim, check_symmetric_max)
  File "/Users/adefusco/Applications/miniconda3/envs/hv5/lib/python3.6/site-packages/hvplot/converter.py", line 513, in _process_symmetric
    cmin = np.nanquantile(data, 0.05)
AttributeError: module 'numpy' has no attribute 'nanquantile'
```

**Comment by philippjfr** [comment]
Tbh, instead of requiring that let's just make our own wrapper around quantile which handles nans, e.g.:

```python
def nanquantile(data, q):
    return np.quantile(data[np.isfinite(data)], q)
```

**Comment by philippjfr** [comment]
We've pinned NumPy. It's hard to get a robust nanquantile to work.
