### ISSUE TITLE
Sample data airline_flights not imported in windows

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/hvplot#562]
#### ALL software version info
Windows 10
hvplot 0.7.0
intake 0.6.1              
intake-parquet  0.2.3                   
intake-xarray 0.4.1

#### Description of expected behavior and the observed behavior
Trying to run the notebook for https://hvplot.holoviz.org/user_guide/Plotting.html, but i cannot get it to work. I suspect it have something to do with `dataset.yaml` and windows path.

A small note is that I was somewhat surprised by the number of extra dependencies I needed to install to run this notebook 
(`intake`,  `intake-parquet`, `intake-xarray`, `s3fs` and `IProgress`).

#### Complete, minimal, self-contained example code that reproduces the issue
``` python
from hvplot.sample_data import airline_flights

flights = airline_flights.to_dask().persists()
```

#### Stack traceback and/or browser JavaScript console output
``` python
Traceback (most recent call last):
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\fastparquet\api.py", line 110, in __init__
    with open_with(fn2, 'rb') as f:
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\fsspec\spec.py", line 937, in open
    f = self._open(
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\fsspec\implementations\local.py", line 118, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\fsspec\implementations\local.py", line 200, in __init__
    self._open()
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\fsspec\implementations\local.py", line 205, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/shh/.intake/cache/7f9708758ba435683113a36d5d76f3db/assets.holoviews.org/data/.parq/_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/shh/Desktop/tmp.py", line 3, in <module>
    flights = airline_flights.to_dask().persists()
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\intake_parquet\source.py", line 99, in to_dask
    self._load_metadata()
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\intake\source\base.py", line 236, in _load_metadata
    self._schema = self._get_schema()
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\intake_parquet\source.py", line 60, in _get_schema
    self._df = self._to_dask()
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\intake_parquet\source.py", line 108, in _to_dask
    self._df = dd.read_parquet(urlpath,
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\dask\dataframe\io\parquet\core.py", line 309, in read_parquet
    read_metadata_result = engine.read_metadata(
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\dask\dataframe\io\parquet\fastparquet.py", line 683, in read_metadata
    parts, pf, gather_statistics, base_path = _determine_pf_parts(
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\dask\dataframe\io\parquet\fastparquet.py", line 184, in _determine_pf_parts
    pf = ParquetFile(
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\fastparquet\api.py", line 115, in __init__
    with open_with(fn, 'rb') as f:
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\fsspec\spec.py", line 937, in open
    f = self._open(
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\fsspec\implementations\local.py", line 118, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\fsspec\implementations\local.py", line 200, in __init__
    self._open()
  File "C:\Users\shh\miniconda3\envs\pressoh\lib\site-packages\fsspec\implementations\local.py", line 205, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/shh/.intake/cache/7f9708758ba435683113a36d5d76f3db/assets.holoviews.org/data/.parq'
```

**Comment by akhtar-shah** [comment]
I also have this issue. I can also not run the same notebook, and I was also surprised by the number of dependencies that needed to be installed. Any solutions?
