### ISSUE TITLE
Row type object not recognized and cannot be shown.

### ISSUE THREAD

**Issue by ghost** [holoviz/hvplot#685]
hi-,

I'm running the sample below with Python Command Prompt.

https://hvplot.holoviz.org/user_guide/Widgets.html
```
import panel as pn
import hvplot.pandas  # noqa

from bokeh.sampledata.iris import flowers

fl = flowers.hvplot.bivariate(x='sepal_width', y='sepal_length', width=600, groupby='species')

hvplot.show(fl)
```

This works fine.

Then I add the widget_location option.

```
import panel as pn
import hvplot.pandas  # noqa

from bokeh.sampledata.iris import flowers

fl = flowers.hvplot.bivariate(x='sepal_width', y='sepal_length', width=600, 
                        groupby='species', widget_location='left_top')

hvplot.show(fl)
```
When I run the code, hvplot.show throws an exception.

ValueError
Row type object not recognized and cannot be shown.

Am I overlooking something ...?
Thank you for your help.

#### ALL software version info
OS:Windows 10 21H1
Anaconda Enviroment:
 hvplot 0.7.3
 pandas 1.3.4
 bokeh 2.3.3
 python 3.9.7

#### Stack traceback and/or browser JavaScript console output
Traceback (most recent call last):
  File "D:\Anaconda3\envs\netcdf4\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\netcdf4\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\mamoru\.vscode\extensions\ms-python.python-2021.11.1422169775\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\mamoru\.vscode\extensions\ms-python.python-2021.11.1422169775\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\mamoru\.vscode\extensions\ms-python.python-2021.11.1422169775\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "D:\Anaconda3\envs\netcdf4\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Anaconda3\envs\netcdf4\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Anaconda3\envs\netcdf4\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "d:\work\Python\test.py", line 9, in <module>
    hvplot.show(fl)
  File "D:\Anaconda3\envs\netcdf4\lib\site-packages\hvplot\utilities.py", line 24, in show
    raise ValueError('%s type object not recognized and cannot be shown.' %
ValueError: Row type object not recognized and cannot be shown.
(netcdf4) PS D:\work\Python>

**Comment by maximlt** [comment]
Hi @MamoruSSoft, no indeed that seems like a bug! Apparently the `show` utility only works when the object returned by `hvplot` is a pure `holoviews` object, while in this case it happens to be a `panel` object. The utility should cover that case imo.

As a workaround you can replace the last line of your code with:
```python
fl.show()
```

This is working because viewable `panel` objects like `fl` have a `show` method.

**Comment by MamoruSSoft** [comment]
@maximlt Thank you for your help, `fl.show` worked fine, I have solved the problem😄
