### ISSUE TITLE
Make it very clear that `hist` only support numerical or datetime fields

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#906]
I'm trying to show that it is much easier to use the HoloViz ecosystem to develop something like https://www.youtube.com/watch?v=htXgwEXwmNs with crossfiltering.

One of the plots is a plotly `histogram`.

It works like

```python
import plotly.express as px
df = px.data.tips()
px.histogram(df, "day", height=400,)
```

But if I run

```python
import plotly.express as px
import hvplot.pandas
df = px.data.tips()
df.hvplot.hist("day", height=400)
```

I get

```bash
numpy.core._exceptions._UFuncNoLoopError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U3'), dtype('float64')) -> None
```

This is not a useful error message and took me quite some time to figure out what was wrong. Pandas `.plot` handles this much nicer.

```python
import plotly.express as px
df = px.data.tips()
df.hist("day", height=400)
```

```bash
ValueError: hist method requires numerical or datetime columns, nothing to plot.
```

**Please provide a similar useful error message and document it in the reference guide and docstring. Thanks.**

## Additional Context

The next issue is that I should then probably do my own aggregations and use HoloViews `bars` which does not support linked selections. Hmmmm. Its not easy.

**Comment by maximlt** [comment]
This is the full traceback:

```
Traceback (most recent call last):
  File "/Users/mliquet/miniconda3/envs/hvplot-dev38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/c9/s6_8wl553ql93tjgvmbmsn5h0000gp/T/ipykernel_26561/3347758194.py", line 1, in <cell line: 1>
    df.hvplot.hist("day", height=400)
  File "/Users/mliquet/work/dev/hvplot/hvplot/plotting/core.py", line 1071, in hist
    return self(kind="hist", x=None, y=y, by=by, **kwds)
  File "/Users/mliquet/work/dev/hvplot/hvplot/plotting/core.py", line 130, in __call__
    return self._get_converter(x, y, kind, **kwds)(kind, x, y)
  File "/Users/mliquet/work/dev/hvplot/hvplot/converter.py", line 1228, in __call__
    obj = method(x, y)
  File "/Users/mliquet/work/dev/hvplot/hvplot/converter.py", line 1808, in hist
    hists = histogram(ds, dimension=y, **hist_opts)
  File "/Users/mliquet/miniconda3/envs/hvplot-dev38/lib/python3.8/site-packages/param/parameterized.py", line 3654, in __new__
    return inst.__call__(*args,**params)
  File "/Users/mliquet/miniconda3/envs/hvplot-dev38/lib/python3.8/site-packages/holoviews/core/operation.py", line 220, in __call__
    return element.apply(self, **kwargs)
  File "/Users/mliquet/miniconda3/envs/hvplot-dev38/lib/python3.8/site-packages/holoviews/core/accessors.py", line 45, in pipelined_call
    result = __call__(*args, **kwargs)
  File "/Users/mliquet/miniconda3/envs/hvplot-dev38/lib/python3.8/site-packages/holoviews/core/accessors.py", line 202, in __call__
    new_obj = apply_function(self._obj, **inner_kwargs)
  File "/Users/mliquet/miniconda3/envs/hvplot-dev38/lib/python3.8/site-packages/holoviews/core/operation.py", line 214, in __call__
    return self._apply(element)
  File "/Users/mliquet/miniconda3/envs/hvplot-dev38/lib/python3.8/site-packages/holoviews/core/operation.py", line 141, in _apply
    ret = self._process(element, key)
  File "/Users/mliquet/miniconda3/envs/hvplot-dev38/lib/python3.8/site-packages/holoviews/operation/element.py", line 797, in _process
    edges = np.linspace(start, end, steps)
  File "<__array_function__ internals>", line 180, in linspace
  File "/Users/mliquet/miniconda3/envs/hvplot-dev38/lib/python3.8/site-packages/numpy/core/function_base.py", line 127, in linspace
    start = asanyarray(start) * 1.0
numpy.core._exceptions._UFuncNoLoopError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U3'), dtype('float64')) -> None
```

@jlstevens do you think improving the error message should be done in HoloViews?

**Comment by philippjfr** [comment]
Yes, the holoviews operation should check dtypes.
