### ISSUE TITLE
hvplot incompatible with bokeh 3.0.1, 3.0.2

### ISSUE THREAD

**Issue by Timothy-W-Hilton** [holoviz/hvplot#970]
Thanks for all your excellent work with holoviz.

Seems there's an incompatibility between hvplot and bokeh 3.0.  The below shows results for bokeh 3.0.2; bokeh 3.0.1 gives me the same result. bokeh 2.4.3 works fine.

#### ALL software version info
(this library, plus any other relevant software, e.g. bokeh, python, notebook, OS, browser, etc)

hvplot                    0.8.1
bokeh                     3.0.2
python                    3.10.6
Ubuntu 20.04.5 LTS
conda 4.1.2, condaforge channel (both via miniforge)

#### Description of expected behavior and the observed behavior

installing hvplot in a minimal conda environment results in an ImportError on `import hvplot`:
> ImportError: cannot import name 'Box' from 'bokeh.models' (/home/timh/mambaforge/envs/venv-test/lib/python3.10/site-packages/bokeh/models/__init__.py)

#### Complete, minimal, self-contained example code that reproduces the issue

```
mamba create -n venv-test python=3.10 bokeh hvplot
conda activate venv-test
python
>>> import hvplot
```

If I specify bokeh v2.4.3 it works fine:

```
mamba create -n venv-test python=3.10 bokeh=2.4.3 hvplot
conda activate venv-test
python
>>> import hvplot
```

#### Stack traceback and/or browser JavaScript console output
>>> import hvplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/timh/mambaforge/envs/venv-test/lib/python3.10/site-packages/hvplot/__init__.py", line 65, in <module>
    import panel as _pn
  File "/home/timh/mambaforge/envs/venv-test/lib/python3.10/site-packages/panel/__init__.py", line 3, in <module>
    from . import layout # noqa
  File "/home/timh/mambaforge/envs/venv-test/lib/python3.10/site-packages/panel/layout/__init__.py", line 1, in <module>
    from .accordion import Accordion # noqa
  File "/home/timh/mambaforge/envs/venv-test/lib/python3.10/site-packages/panel/layout/accordion.py", line 5, in <module>
    from .base import NamedListPanel
  File "/home/timh/mambaforge/envs/venv-test/lib/python3.10/site-packages/panel/layout/base.py", line 13, in <module>
    from ..io.model import hold
  File "/home/timh/mambaforge/envs/venv-test/lib/python3.10/site-packages/panel/io/__init__.py", line 8, in <module>
    from ..config import config
  File "/home/timh/mambaforge/envs/venv-test/lib/python3.10/site-packages/panel/config.py", line 20, in <module>
    from .io.notebook import load_notebook
  File "/home/timh/mambaforge/envs/venv-test/lib/python3.10/site-packages/panel/io/notebook.py", line 40, in <module>
    from .embed import embed_state
  File "/home/timh/mambaforge/envs/venv-test/lib/python3.10/site-packages/panel/io/embed.py", line 20, in <module>
    from .model import add_to_doc, diff
  File "/home/timh/mambaforge/envs/venv-test/lib/python3.10/site-packages/panel/io/model.py", line 11, in <module>
    from bokeh.models import Box, ColumnDataSource, Model
ImportError: cannot import name 'Box' from 'bokeh.models' (/home/timh/mambaforge/envs/venv-test/lib/python3.10/site-packages/bokeh/models/__init__.py)

**Comment by maximlt** [comment]
Could you please report what HoloViews version was installed?

**Comment by philippjfr** [comment]
hvPlot, HoloViews and Panel will not be 3.0 compatible until some time around January. There have been major changes in Bokeh 3.0 that we have to adapt to and as of 3.0.x there is some functionality missing that won't allow us to upgrade.

**Comment by Timothy-W-Hilton** [comment]
> Could you please report what HoloViews version was installed?

holoviews was 1.14.9

Thanks, @philippjfr, good to know.  

Thanks as always to the whole holoviz team for all your work on this!

**Comment by maximlt** [comment]
Oh another question if you don't mind, which version of `mamba` do you use?

**Comment by Timothy-W-Hilton** [comment]
@maximlt, I have mamba 0.22.1, conda 4.12.0
