### ISSUE TITLE
hvplot not working in vs code

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/hvplot#983]
I've just created a new virtual environment (.venv, python 3.10) with hvplot 0.8.2. 

And it fails when I try to use it in the VS Code Interactive Jupyter window.

![image](https://user-images.githubusercontent.com/42288570/203973718-edd02036-a12d-4b9f-99be-a5ab822aa2c2.png)

```python
import hvplot.pandas
```

```bash
Traceback (most recent call last):
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-d0834c846347>", line 1, in <module>
    import hvplot.pandas
  File "/home/jovyan/repos/private/hvplot/hvplot/pandas.py", line 25, in <module>
    patch()
  File "/home/jovyan/repos/private/hvplot/hvplot/pandas.py", line 23, in patch
    post_patch(extension, logo)
  File "/home/jovyan/repos/private/hvplot/hvplot/__init__.py", line 166, in post_patch
    hvplot_extension(extension, logo=logo)
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/pyviz_comms/__init__.py", line 64, in __new__
    return param.ParameterizedFunction.__new__(cls, *args, **kwargs)
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/param/parameterized.py", line 3654, in __new__
    return inst.__call__(*args,**params)
  File "/home/jovyan/repos/private/hvplot/hvplot/utilities.py", line 45, in __call__
    super().__call__(*args, **params)
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/holoviews/ipython/__init__.py", line 149, in __call__
    ip.run_line_magic('config', 'IPCompleter.use_jedi = False')
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2364, in run_line_magic
    result = fn(*args, **kwargs)
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/IPython/core/magics/config.py", line 163, in config
    configurables = sorted(set([ c for c in self.shell.configurables
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/IPython/core/magics/config.py", line 164, in <listcomp>
    if c.__class__.class_traits(config=True)
AttributeError: type object 'CommManager' has no attribute 'class_traits'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2052, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1112, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1006, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/IPython/core/ultratb.py", line 859, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/IPython/core/ultratb.py", line 812, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/IPython/core/ultratb.py", line 730, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/stack_data/core.py", line 720, in lines
    pieces = self.included_pieces
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/stack_data/core.py", line 663, in included_pieces
    scope_pieces = self.scope_pieces
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/stack_data/core.py", line 603, in scope_pieces
    for piece in self.source.pieces
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/stack_data/core.py", line 101, in pieces
    return list(self._clean_pieces())
  File "/home/jovyan/repos/private/hvplot/.venv/lib/python3.10/site-packages/stack_data/core.py", line 125, in _clean_pieces
    raise AssertionError("Pieces mismatches: %s" % mismatches)
AssertionError: Pieces mismatches: [{680, 681}, {696, 695}, {708, 709}, {714, 715}]

```

**Comment by MarcSkovMadsen** [comment]
I have ipython 8.6.0 installed.

**Comment by Hoxbro** [comment]
Downgrade ipykernel to  6.17.1.

**Comment by MarcSkovMadsen** [comment]
Thanks. Should hvplot pin ipykernel<=6.17.1 for now. Any user making a fresh install would be affected currently.

**Comment by Hoxbro** [comment]
The package has been yanked from pypi and marked as broken on conda-forge. A new release of ipykernel will be released at the start of next week. So I don't think there is anything to do, other than wait.

**Comment by dwr-psandhu** [comment]
Same issue on mac m1 install of ipykernel and hvplot ...

**Comment by MarcSkovMadsen** [comment]
Try to downgrade ipykernel to 6.17.1.

see #981

**Comment by dwr-psandhu** [comment]
Downgrade worked. 

> Try to downgrade ipykernel to 6.17.1.
> 
> see #981

**Comment by maximlt** [comment]
Closing as the problematic version of ipykernel has been removed.
